FROM node:22-bookworm


ARG NEXT_PUBLIC_TILE_SERVER_URL
ENV NEXT_PUBLIC_TILE_SERVER_URL $NEXT_PUBLIC_TILE_SERVER_URL


ARG ENV_MODE
ENV ENV_MODE $ENV_MODE

ARG JWT_SECRET
ENV JWT_SECRET $JWT_SECRET

ARG DATABASE_URL
ENV DATABASE_URL $DATABASE_URL

ARG GRAPHQL_ENDPOINT
ENV GRAPHQL_ENDPOINT $GRAPHQL_ENDPOINT

ARG SUDO_PASSWORD
ENV SUDO_PASSWORD $SUDO_PASSWORD

ARG N8N_ENCRYPTION_KEY
ENV N8N_ENCRYPTION_KEY $N8N_ENCRYPTION_KEY

ARG NEXT_PUBLIC_TELEGRAM_BOT_NAME
ENV NEXT_PUBLIC_TELEGRAM_BOT_NAME $NEXT_PUBLIC_TELEGRAM_BOT_NAME

ARG NEXT_PUBLIC_DEBUG_WORLD3D
ENV NEXT_PUBLIC_DEBUG_WORLD3D $NEXT_PUBLIC_DEBUG_WORLD3D

ARG NEXT_PUBLIC_POSTS_ENABLED
ENV NEXT_PUBLIC_POSTS_ENABLED $NEXT_PUBLIC_POSTS_ENABLED

ARG NEXT_PUBLIC_WORLD3D_ENABLED
ENV NEXT_PUBLIC_WORLD3D_ENABLED $NEXT_PUBLIC_WORLD3D_ENABLED

ARG NEXT_PUBLIC_CRYPTO_ENABLED
ENV NEXT_PUBLIC_CRYPTO_ENABLED $NEXT_PUBLIC_CRYPTO_ENABLED

ARG NEXT_PUBLIC_MAIN_PAGE_TITLE
ENV NEXT_PUBLIC_MAIN_PAGE_TITLE $NEXT_PUBLIC_MAIN_PAGE_TITLE

ARG NEXT_PUBLIC_SITE_SIGNUP_STRATEGY
ENV NEXT_PUBLIC_SITE_SIGNUP_STRATEGY $NEXT_PUBLIC_SITE_SIGNUP_STRATEGY

ARG NEXT_PUBLIC_BETTERLYTICS_SITE_ID
ENV NEXT_PUBLIC_BETTERLYTICS_SITE_ID $NEXT_PUBLIC_BETTERLYTICS_SITE_ID

ARG NEXT_PUBLIC_BETTERLYTICS_SCRIPT_URL
ENV NEXT_PUBLIC_BETTERLYTICS_SCRIPT_URL $NEXT_PUBLIC_BETTERLYTICS_SCRIPT_URL

ARG NEXT_PUBLIC_BETTERLYTICS_SERVER_URL
ENV NEXT_PUBLIC_BETTERLYTICS_SERVER_URL $NEXT_PUBLIC_BETTERLYTICS_SERVER_URL

ARG NEXT_USE_TURBOPACK
ENV NEXT_USE_TURBOPACK $NEXT_USE_TURBOPACK


# ARG GRAPHQL_API_ENDPOINT
# ENV GRAPHQL_API_ENDPOINT $GRAPHQL_API_ENDPOINT

RUN apt-get update && apt-get install -y \
    curl \
    sudo \
    git \
    jq \
    mc \
    nmap \
    libvips-dev \
    build-essential \
    python3 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci

# RUN npx playwright install --with-deps

# Copy source
COPY . .

RUN npm run prisma:deploy && npm run generate && npm run prisma:seed

RUN if [ "$ENV_MODE" = "production" ] ; then yarn build ; fi

# Expose ports
EXPOSE 3000 4000
