import type { SelectOption } from 'src/ui-kit/controls/Select'

// Official Gemini TTS lists, checked 2026-09-20:
// https://ai.google.dev/gemini-api/docs/speech-generation#supported-languages
// https://ai.google.dev/gemini-api/docs/speech-generation#voice-options
// Voices also verified against OpenRouter's supported_voices:
// https://openrouter.ai/api/v1/models?output_modalities=speech
export const GEMINI_TTS_MODEL = 'google/gemini-3.1-flash-tts-preview'

export enum GeminiTtsLanguage {
  Arabic = 'ar',
  Filipino = 'fil',
  Bangla = 'bn',
  Finnish = 'fi',
  Dutch = 'nl',
  Galician = 'gl',
  English = 'en',
  Georgian = 'ka',
  French = 'fr',
  Greek = 'el',
  German = 'de',
  Gujarati = 'gu',
  Hindi = 'hi',
  HaitianCreole = 'ht',
  Indonesian = 'id',
  Hebrew = 'he',
  Italian = 'it',
  Hungarian = 'hu',
  Japanese = 'ja',
  Icelandic = 'is',
  Korean = 'ko',
  Javanese = 'jv',
  Marathi = 'mr',
  Kannada = 'kn',
  Polish = 'pl',
  Konkani = 'kok',
  Portuguese = 'pt',
  Lao = 'lo',
  Romanian = 'ro',
  Latin = 'la',
  Russian = 'ru',
  Latvian = 'lv',
  Spanish = 'es',
  Lithuanian = 'lt',
  Tamil = 'ta',
  Luxembourgish = 'lb',
  Telugu = 'te',
  Macedonian = 'mk',
  Thai = 'th',
  Maithili = 'mai',
  Turkish = 'tr',
  Malagasy = 'mg',
  Ukrainian = 'uk',
  Malay = 'ms',
  Vietnamese = 'vi',
  Malayalam = 'ml',
  Afrikaans = 'af',
  Mongolian = 'mn',
  Albanian = 'sq',
  Nepali = 'ne',
  Amharic = 'am',
  NorwegianBokmal = 'nb',
  Armenian = 'hy',
  NorwegianNynorsk = 'nn',
  Azerbaijani = 'az',
  Odia = 'or',
  Basque = 'eu',
  Pashto = 'ps',
  Belarusian = 'be',
  Persian = 'fa',
  Bulgarian = 'bg',
  Punjabi = 'pa',
  Burmese = 'my',
  Serbian = 'sr',
  Catalan = 'ca',
  Sindhi = 'sd',
  Cebuano = 'ceb',
  Sinhala = 'si',
  MandarinChinese = 'cmn',
  Slovak = 'sk',
  Croatian = 'hr',
  Slovenian = 'sl',
  Czech = 'cs',
  Swahili = 'sw',
  Danish = 'da',
  Swedish = 'sv',
  Estonian = 'et',
  Urdu = 'ur',
}

export enum GeminiTtsVoice {
  Zephyr = 'Zephyr',
  Puck = 'Puck',
  Charon = 'Charon',
  Kore = 'Kore',
  Fenrir = 'Fenrir',
  Leda = 'Leda',
  Orus = 'Orus',
  Aoede = 'Aoede',
  Callirrhoe = 'Callirrhoe',
  Autonoe = 'Autonoe',
  Enceladus = 'Enceladus',
  Iapetus = 'Iapetus',
  Umbriel = 'Umbriel',
  Algieba = 'Algieba',
  Despina = 'Despina',
  Erinome = 'Erinome',
  Algenib = 'Algenib',
  Rasalgethi = 'Rasalgethi',
  Laomedeia = 'Laomedeia',
  Achernar = 'Achernar',
  Alnilam = 'Alnilam',
  Schedar = 'Schedar',
  Gacrux = 'Gacrux',
  Pulcherrima = 'Pulcherrima',
  Achird = 'Achird',
  Zubenelgenubi = 'Zubenelgenubi',
  Vindemiatrix = 'Vindemiatrix',
  Sadachbia = 'Sadachbia',
  Sadaltager = 'Sadaltager',
  Sulafat = 'Sulafat',
}

const languageLabels: Record<GeminiTtsLanguage, string> = {
  [GeminiTtsLanguage.Arabic]: 'Arabic',
  [GeminiTtsLanguage.Filipino]: 'Filipino',
  [GeminiTtsLanguage.Bangla]: 'Bangla',
  [GeminiTtsLanguage.Finnish]: 'Finnish',
  [GeminiTtsLanguage.Dutch]: 'Dutch',
  [GeminiTtsLanguage.Galician]: 'Galician',
  [GeminiTtsLanguage.English]: 'English',
  [GeminiTtsLanguage.Georgian]: 'Georgian',
  [GeminiTtsLanguage.French]: 'French',
  [GeminiTtsLanguage.Greek]: 'Greek',
  [GeminiTtsLanguage.German]: 'German',
  [GeminiTtsLanguage.Gujarati]: 'Gujarati',
  [GeminiTtsLanguage.Hindi]: 'Hindi',
  [GeminiTtsLanguage.HaitianCreole]: 'Haitian Creole',
  [GeminiTtsLanguage.Indonesian]: 'Indonesian',
  [GeminiTtsLanguage.Hebrew]: 'Hebrew',
  [GeminiTtsLanguage.Italian]: 'Italian',
  [GeminiTtsLanguage.Hungarian]: 'Hungarian',
  [GeminiTtsLanguage.Japanese]: 'Japanese',
  [GeminiTtsLanguage.Icelandic]: 'Icelandic',
  [GeminiTtsLanguage.Korean]: 'Korean',
  [GeminiTtsLanguage.Javanese]: 'Javanese',
  [GeminiTtsLanguage.Marathi]: 'Marathi',
  [GeminiTtsLanguage.Kannada]: 'Kannada',
  [GeminiTtsLanguage.Polish]: 'Polish',
  [GeminiTtsLanguage.Konkani]: 'Konkani',
  [GeminiTtsLanguage.Portuguese]: 'Portuguese',
  [GeminiTtsLanguage.Lao]: 'Lao',
  [GeminiTtsLanguage.Romanian]: 'Romanian',
  [GeminiTtsLanguage.Latin]: 'Latin',
  [GeminiTtsLanguage.Russian]: 'Russian',
  [GeminiTtsLanguage.Latvian]: 'Latvian',
  [GeminiTtsLanguage.Spanish]: 'Spanish',
  [GeminiTtsLanguage.Lithuanian]: 'Lithuanian',
  [GeminiTtsLanguage.Tamil]: 'Tamil',
  [GeminiTtsLanguage.Luxembourgish]: 'Luxembourgish',
  [GeminiTtsLanguage.Telugu]: 'Telugu',
  [GeminiTtsLanguage.Macedonian]: 'Macedonian',
  [GeminiTtsLanguage.Thai]: 'Thai',
  [GeminiTtsLanguage.Maithili]: 'Maithili',
  [GeminiTtsLanguage.Turkish]: 'Turkish',
  [GeminiTtsLanguage.Malagasy]: 'Malagasy',
  [GeminiTtsLanguage.Ukrainian]: 'Ukrainian',
  [GeminiTtsLanguage.Malay]: 'Malay',
  [GeminiTtsLanguage.Vietnamese]: 'Vietnamese',
  [GeminiTtsLanguage.Malayalam]: 'Malayalam',
  [GeminiTtsLanguage.Afrikaans]: 'Afrikaans',
  [GeminiTtsLanguage.Mongolian]: 'Mongolian',
  [GeminiTtsLanguage.Albanian]: 'Albanian',
  [GeminiTtsLanguage.Nepali]: 'Nepali',
  [GeminiTtsLanguage.Amharic]: 'Amharic',
  [GeminiTtsLanguage.NorwegianBokmal]: 'Norwegian, Bokmål',
  [GeminiTtsLanguage.Armenian]: 'Armenian',
  [GeminiTtsLanguage.NorwegianNynorsk]: 'Norwegian, Nynorsk',
  [GeminiTtsLanguage.Azerbaijani]: 'Azerbaijani',
  [GeminiTtsLanguage.Odia]: 'Odia',
  [GeminiTtsLanguage.Basque]: 'Basque',
  [GeminiTtsLanguage.Pashto]: 'Pashto',
  [GeminiTtsLanguage.Belarusian]: 'Belarusian',
  [GeminiTtsLanguage.Persian]: 'Persian',
  [GeminiTtsLanguage.Bulgarian]: 'Bulgarian',
  [GeminiTtsLanguage.Punjabi]: 'Punjabi',
  [GeminiTtsLanguage.Burmese]: 'Burmese',
  [GeminiTtsLanguage.Serbian]: 'Serbian',
  [GeminiTtsLanguage.Catalan]: 'Catalan',
  [GeminiTtsLanguage.Sindhi]: 'Sindhi',
  [GeminiTtsLanguage.Cebuano]: 'Cebuano',
  [GeminiTtsLanguage.Sinhala]: 'Sinhala',
  [GeminiTtsLanguage.MandarinChinese]: 'Chinese, Mandarin',
  [GeminiTtsLanguage.Slovak]: 'Slovak',
  [GeminiTtsLanguage.Croatian]: 'Croatian',
  [GeminiTtsLanguage.Slovenian]: 'Slovenian',
  [GeminiTtsLanguage.Czech]: 'Czech',
  [GeminiTtsLanguage.Swahili]: 'Swahili',
  [GeminiTtsLanguage.Danish]: 'Danish',
  [GeminiTtsLanguage.Swedish]: 'Swedish',
  [GeminiTtsLanguage.Estonian]: 'Estonian',
  [GeminiTtsLanguage.Urdu]: 'Urdu',
}

const voiceDescriptions: Record<GeminiTtsVoice, string> = {
  [GeminiTtsVoice.Zephyr]: 'Bright',
  [GeminiTtsVoice.Puck]: 'Upbeat',
  [GeminiTtsVoice.Charon]: 'Informative',
  [GeminiTtsVoice.Kore]: 'Firm',
  [GeminiTtsVoice.Fenrir]: 'Excitable',
  [GeminiTtsVoice.Leda]: 'Youthful',
  [GeminiTtsVoice.Orus]: 'Firm',
  [GeminiTtsVoice.Aoede]: 'Breezy',
  [GeminiTtsVoice.Callirrhoe]: 'Easy-going',
  [GeminiTtsVoice.Autonoe]: 'Bright',
  [GeminiTtsVoice.Enceladus]: 'Breathy',
  [GeminiTtsVoice.Iapetus]: 'Clear',
  [GeminiTtsVoice.Umbriel]: 'Easy-going',
  [GeminiTtsVoice.Algieba]: 'Smooth',
  [GeminiTtsVoice.Despina]: 'Smooth',
  [GeminiTtsVoice.Erinome]: 'Clear',
  [GeminiTtsVoice.Algenib]: 'Gravelly',
  [GeminiTtsVoice.Rasalgethi]: 'Informative',
  [GeminiTtsVoice.Laomedeia]: 'Upbeat',
  [GeminiTtsVoice.Achernar]: 'Soft',
  [GeminiTtsVoice.Alnilam]: 'Firm',
  [GeminiTtsVoice.Schedar]: 'Even',
  [GeminiTtsVoice.Gacrux]: 'Mature',
  [GeminiTtsVoice.Pulcherrima]: 'Forward',
  [GeminiTtsVoice.Achird]: 'Friendly',
  [GeminiTtsVoice.Zubenelgenubi]: 'Casual',
  [GeminiTtsVoice.Vindemiatrix]: 'Gentle',
  [GeminiTtsVoice.Sadachbia]: 'Lively',
  [GeminiTtsVoice.Sadaltager]: 'Knowledgeable',
  [GeminiTtsVoice.Sulafat]: 'Warm',
}

export const geminiTtsLanguageOptions: SelectOption[] = [
  { value: '', label: 'Auto — detect from text' },
  ...Object.values(GeminiTtsLanguage)
    .map((value) => ({ value, label: `${languageLabels[value]} (${value})` }))
    .sort((a, b) => a.label.localeCompare(b.label, 'en')),
]

export const geminiTtsVoiceOptions: SelectOption[] = Object.values(
  GeminiTtsVoice,
)
  .map((value) => ({ value, label: `${value} — ${voiceDescriptions[value]}` }))
  .sort((a, b) => a.label.localeCompare(b.label, 'en'))
