query concept(
  $where: KBConceptWhereUniqueInput!
  $detailedInfo: Boolean = true
) {
  concept(where: $where) {
    ...KBConcept_
  }
}

query myConcepts(
  $where: KBConceptWhereInput
  $orderBy: KBConceptOrderByInput
  $skip: Int
  $take: Int
  $detailedInfo: Boolean = false
) {
  response: myConcepts(
    where: $where
    orderBy: $orderBy
    skip: $skip
    take: $take
  ) {
    ...KBConcept_
  }
}

query myConcept($id: String!, $detailedInfo: Boolean = true) {
  response: myConcept(id: $id) {
    ...KBConcept_
  }
}

query concepts(
  $where: KBConceptWhereInput
  $orderBy: KBConceptOrderByInput
  $skip: Int
  $take: Int
  $detailedInfo: Boolean = true
) {
  response: concepts(
    where: $where
    orderBy: $orderBy
    skip: $skip
    take: $take
  ) {
    ...KBConcept_
  }
}

query conceptsCount($where: KBConceptWhereInput) {
  kBConceptsCount(where: $where)
}

query conceptsConnection(
  $where: KBConceptWhereInput
  $orderBy: KBConceptOrderByInput
  $skip: Int
  $take: Int
  $detailedInfo: Boolean = false
) {
  concepts(where: $where, orderBy: $orderBy, skip: $skip, take: $take) {
    ...KBConcept_
  }
  kBConceptsCount(where: $where)
}

mutation createConcept(
  $data: KBConceptCreateInput!
  $detailedInfo: Boolean = true
) {
  response: createConcept(data: $data) {
    ...KBConcept_
  }
}

mutation updateConcept(
  $where: KBConceptWhereUniqueInput!
  $data: KBConceptUpdateInput!
  $detailedInfo: Boolean = true
) {
  response: updateConcept(where: $where, data: $data) {
    ...KBConcept_
  }
}

mutation deleteConcept($id: String!) {
  response: deleteConcept(id: $id) {
    id
  }
}

mutation uploadKbConcept(
  $data: KbConceptUploadInput!
  $detailedInfo: Boolean = true
) {
  response: uploadKbConcept(data: $data) {
    ...KBConcept_
  }
}

fragment KBConceptNoNesting on KBConcept {
  id
  # createdAt
  updatedAt
  type
  name
  description
  intro
  image
  createdById
  code
  parentId
  rootId
  uri
  path
  quality
  visibility
  data
  lat
  lng
  content @include(if: $detailedInfo)
}

fragment KBConcept_ on KBConcept {
  ...KBConceptNoNesting
  CreatedBy {
    ...UserNoNesting
  }
}
