mutation llmImageGeneration($input: LLMImageGenerationInput!) {
  llmImageGeneration(input: $input) {
    ...LLMResponse_
  }
}

mutation llmChatCompletion($input: LLMChatCompletionInput!) {
  response: llmChatCompletion(input: $input) {
    ...LLMResponse_
  }
}

fragment LLMResponse_ on LLMResponse {
  choices {
    index
    message {
      role
      content
      images {
        imageUrl
      }
    }
  }
  usage {
    totalTokens
    promptTokens
    completionTokens
    cost
    costDetails {
      upstreamInferenceCompletionsCost
      upstreamInferenceCost
      upstreamInferencePromptCost
    }
  }
}

mutation llmSpeechGeneration($input: LLMSpeechGenerationInput!) {
  llmSpeechGeneration(input: $input) {
    id
    audioUrl
    mimeType
    format
  }
}
